### ISSUE TITLE
[Tests] Flaky TxClient tests

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#425]
## Objective

Have a non-flaky `TxClient_SignAndBroadcast_Succeeds` that doesn't arbitrarily fail.

Running `make itest 5 10 ./pkg/client/tx/... -- -run TxClient_SignAndBroadcast_Succeeds` should have a deterministic outcome.

## Origin Document

This specific test is arbitrarily failing making unit and CI tests failing too often with false positives and requiring us to run them again.

![image](https://github.com/pokt-network/poktroll/assets/231488/fa2bc74f-99d6-4d62-b802-87986af20525)

## Goals

- Restructure the `TxClient_SignAndBroadcast_Succeeds` test and make it have a deterministic outcome
-  Confirm whether the issue is with the test itself or with the code being testsd.

## Deliverables

- [ ] A single PR fixing the `TxClient_SignAndBroadcast_Succeeds` test on `pkg/client/tx/client_test.go`.
- [ ] Add comments explaining why it's happening and how it is solved.

## Non-goals / Non-deliverables

- Refactor the tested code
- Complete rewrite of the test

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @red-0ne 
**Co-Owners**: @Olshansk @bryanchriswhite

**Comment by red-0ne** [comment]
My investigation led me to think that the issue is that `err, ok := <-errCh` in [pkg/client/tx/client_test.go#L137](https://github.com/pokt-network/poktroll/blob/feat/proof-validation/pkg/client/tx/client_test.go#L137) fails to emit making the test to timeout.

This happens because `txResultsBzPublishCh <- either.Success[[]byte](rpcResultBz)` in [pkg/client/tx/client_test.go#L132](https://github.com/pokt-network/poktroll/blob/feat/proof-validation/pkg/client/tx/client_test.go#L132) is blocked or late to receive its value, which in turn blocks closing the `txErrCh` in [pkg/client/tx/client.go#L423](https://github.com/pokt-network/poktroll/blob/main/pkg/client/tx/client.go#L423)

**Comment by Olshansk** [comment]
@red-0ne Appreciate the details and offline discussion. I've started putting together #428 with some pointers of where to look but the takeaway is that we have to improve testing related to the Observable.

In terms of next steps:
1. @red-0ne and @Olshansk to keep looking into this either together or independently (we'll prioritize next week).
2. Calling out that we need to do (1) WITHOUT @bryanchriswhite and @h5law because our "fresh and uninformed perspective" is key to understanding how to improve this (helpers, docs, interface, etc...).
3. After we do (1) following the rules in (2), all of us together can figure out what the best next step is (refactoring, updating, interfaces, etc...).

**Comment by red-0ne** [comment]
#444 should have tackled this.

Reopen if it still persists.
